### ISSUE TITLE
Project build with run. (windows and linux)

### ISSUE THREAD

**Issue by ghost** [hholzgra/connector-c-examples#3]
Hi.
I wrote the following code based on your MySQL access demo.
I want to run this to create a database.
Please give me some advice to build this program.
Written in *.c in Visual Studio 2019.
Is it executable in Visual Studio 2019?
Which field of Visual Studio 2019 should you try to create?
What is MySQL library?
Isn't my.CNF file possible in Ubuntu system?
How do I build and run this on Ubuntu?
Please explain it step by step.
Thank you.

#include <errno.h>
#include <fcntl.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/epoll.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/timerfd.h>
#include <sys/types.h>
#include <sys/resource.h>
#include <sys/socket.h>
#include <arpa/inet.h>
#include <time.h>
#include <unistd.h>
#include <pthread.h>
#include <netdb.h>
#include <time.h>
#include <netinet/in.h>
#include <mysql.h> 
#include <curl/curl.h>
#include <ctype.h>

MYSQL *mysql_con;

void
mysql_start()
{
	mysql_con = mysql_init(NULL);
	if (mysql_con == NULL)
	{
		fprintf(stderr, "%s\n", mysql_error(mysql_con));
		exit(1);
	}

	if (mysql_real_connect(mysql_con, "localhost", "happy", "123456", "happy", 0, NULL, 0) == NULL)
	{
		fprintf(stderr, "%s\n", mysql_error(mysql_con));
		exit(EXIT_FAILURE);
	}

	if (mysql_query(mysql_con, "CREATE TABLE IF NOT EXISTS `frontier` (`url` varchar(2084) NOT NULL, `id` int NOT NULL AUTO_INCREMENT, PRIMARY KEY (`id`), UNIQUE KEY `url` (`url`)) ENGINE=InnoDB AUTO_INCREMENT=1"))
	{
		fprintf(stderr, "%s\n", mysql_error(mysql_con));
		mysql_stop();
                exit(1);
	}

	if (mysql_query(mysql_con, "CREATE TABLE IF NOT EXISTS `crawled` (`id` int NOT NULL AUTO_INCREMENT, `url` varchar(2084) DEFAULT NULL, `title` varchar(768) DEFAULT NULL, `date` varchar(128) DEFAULT NULL, `last_modified` varchar(128) DEFAULT NULL, `links` int DEFAULT NULL, `backlinks` int DEFAULT NULL, `http_code` int DEFAULT NULL, PRIMARY KEY (`id`), UNIQUE KEY `url` (`url`), KEY `http_code` (`http_code`), KEY `title` (`title`)) ENGINE=InnoDB AUTO_INCREMENT=1"))
	{
		fprintf(stderr, "%s\n", mysql_error(mysql_con));
                mysql_stop();
                exit(1);
	}

	if (mysql_query(mysql_con, "CREATE TABLE IF NOT EXISTS `emails` (`email` varchar(2084) NOT NULL, `id` int NOT NULL AUTO_INCREMENT, PRIMARY KEY (`id`), UNIQUE KEY `email` (`email`)) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=latin1"))
	{
		fprintf(stderr, "%s\n", mysql_error(mysql_con));
                mysql_stop();
                exit(1);
	}
}
void
mysql_stop()
{
	mysql_close(mysql_con);
}
int
main(int argc, char **argv)
{
	int cleanup = 0, opt, ret;

	mysql_start();
	mysql_stop();

	printf("Exiting.\n");

	return (0);
}

**Comment by hholzgra** [comment]
This is a pretty old project actually, dating back to when MySQL still used autotools for Unix builds. So things will only work on Unix-like environment.

The auto generated INSTALL file in the repository was lacking instructions how to generate the "configure" file in the first place, I now added the generated "configure" script for convenience (usually it would only be bundled in source release tarballs created by "make dist")

To build on Unix you need a working C compiler setup, GNU make, and MariaDB or MySQL headers and client library. Then you can build and install with just the usual 

`./configure; make; sudo make install`

On Ubuntu this should be sufficient to install all build dependencies:

`sudo apt-get install -y gcc make libmariadb-dev libmariadb-dev-compat`

Sorry, no Windows support unless someone volunteers (or bribes me) to add CMake support.

**Comment by hholzgra** [comment]
I updated the [INSTALL](https://github.com/hholzgra/connector-c-examples/blob/master/INSTALL) file now, and also created a [v1.0.1 release](https://github.com/hholzgra/connector-c-examples/releases/download/v1.0.1/connector-c-examples-1.0.1.tar.gz) with the "configure" script already included (and fixed some minor build issue from v1.0.0, too)
